using SharpFunction.Commands;
using SharpFunction.Writer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SharpFunction.Addons.Skyblock
{
    /// <summary>
    /// Represents skyblock slayer
    /// </summary>
    public sealed class SkyblockSlayer
    {
        /// <summary>
        /// All items related to this slayer
        /// </summary>
        public SkyblockItem[] SlayerItems { get; set; }
        /// <summary>
        /// All slayer boss tiers of the boss
        /// </summary>
        public SlayerTier[] SlayerTiers { get; set; }
        /// <summary>
        /// All slayer drops of the slayer
        /// </summary>
        public SlayerDrop[] SlayerDrops { get; set; }
        /// <summary>
        /// Writer to write datapack functions
        /// </summary>
        public FunctionWriter Writer { get; set; }
        /// <summary>
        /// Minibosses of slayer
        /// </summary>
        public SkyblockEntity[] Minibosses { get; set; }
        /// <summary>
        /// Name of slayer boss
        /// </summary>
        public string SlayerBossName { get; set; }
        /// <summary>
        /// Creates a new slayer
        /// </summary>
        /// <param name="items">Items of slayer</param>
        /// <param name="tiers">Tiers of slayer bosses</param>
        /// <param name="writer">FunctionWriter from project</param>
        /// <param name="name">Name of slayer boss</param>
        public SkyblockSlayer(SkyblockItem[] items, SlayerTier[] tiers, SlayerDrop[] drops, FunctionWriter writer, string name)
        {
            SlayerItems = items;
            SlayerTiers = tiers;
            SlayerDrops = drops;
            Writer = writer;
            SlayerBossName = name;
        }
        /// <summary>
        /// Generate an empty skyblock slayer to add all the data later
        /// </summary>
        public SkyblockSlayer() { }
        /// <summary>
        /// Generates all the required stuff for datapack
        /// </summary>
        public void Generate()
        {
            Writer.CreateCategory($"{SlayerBossName.ToLower().Replace(" ", "_")}_slayer");
            Writer.CreateFunction("items");
            Writer.CreateFunction("drops");
            for (int i = 0; i < SlayerTiers.Length; i++)
            {
                Writer.CreateFunction($"boss_{i+1}");
                CommandModule b = new();
                b.Append($"# This script is used to summon {SlayerBossName} Slayer Tier {i+1}", "# This file is PRE-GENERATED by SharpFunction", " ");
                SlayerTiers[i].Compile();
                b.Append("# Give Item representing the slayer ", $"{SlayerTiers[i].GiveCommand}", "# Summon Command summoning boss", $"{SlayerTiers[i].SummonCommand}");
                Writer.WriteCommand(b, $"boss_{i + 1}");
            }
            CommandModule items = new();
            items.Append($"# This script is used to give all items related to {SlayerBossName} Slayer", "# This file is PRE-GENERATED by SharpFunction", " ");
            CommandModule drops = new();
            drops.Append($"# This script is used to give all drops info related to {SlayerBossName} Slayer", "# This file is PRE-GENERATED by SharpFunction", " ");
            CommandModule minis = new();
            minis.Append($"# This script is used to summon all minibosses/entities related to {SlayerBossName} Slayer", "# This file is PRE-GENERATED by SharpFunction", " ");
            foreach (SkyblockItem it in SlayerItems)
            {
                string i = it.Compile();
                items.Append($"# Gives {it.DisplayName}", i, " ");
            }
            Writer.WriteCommand(items, "items");
            foreach(SlayerDrop dr in SlayerDrops)
            {
                string d = dr.Compile();
                drops.Append($"# Gives drop info item on {dr.ItemName}", d, " ");
                Writer.CreateFunction($"{dr.ItemName.ToLower().Replace(" ", "_")}");
                // TODO: Finish this later
            }
            Writer.WriteCommand(drops, "drops");
            foreach (SkyblockEntity se in Minibosses)
            {
                se.Compile();
                string s = se.Command.Compiled;
                CommandModule sm = new();
                sm.Append($"# Summons {se.Name}", s);
                Writer.CreateFunction($"summon_{se.Name.ToLower().Replace(" ", "_")}");
                Writer.WriteCommand(sm, $"summon_{se.Name.ToLower().Replace(" ", "_")}");
            }
        }
    }
}
