using SharpFunction.Commands;
using SharpFunction.Writer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SharpFunction.Addons.Skyblock
{
    /// <summary>
    /// Represents skyblock slayer
    /// </summary>
    public sealed class SkyblockSlayer
    {
        /// <summary>
        /// All items related to this slayer
        /// </summary>
        public SlayerItem[] SlayerItems { get; set; }
        /// <summary>
        /// All slayer boss tiers of the boss
        /// </summary>
        public SlayerTier[] SlayerTiers { get; set; }
        /// <summary>
        /// Writer to write datapack functions
        /// </summary>
        public FunctionWriter Writer { get; set; }
        /// <summary>
        /// Name of slayer boss
        /// </summary>
        public string SlayerBossName { get; set; }
        /// <summary>
        /// Creates a new slayer
        /// </summary>
        /// <param name="items">Items of slayer</param>
        /// <param name="tiers">Tiers of slayer bosses</param>
        /// <param name="writer">FunctionWriter from project</param>
        /// <param name="name">Name of slayer boss</param>
        public SkyblockSlayer(SlayerItem[] items, SlayerTier[] tiers, FunctionWriter writer, string name)
        {
            SlayerItems = items;
            SlayerTiers = tiers;
            Writer = writer;
            SlayerBossName = name;
        }
        /// <summary>
        /// Generates all the required stuff for datapack
        /// </summary>
        public void Generate()
        {
            Writer.CreateCategory($"slayer_{SlayerBossName.ToLower().Replace(" ", "_")}");
            Writer.CreateFunction("items");
            CommandModule itemModule = new();
            itemModule.Append($"# This script is used to give all items related to {SlayerBossName} Slayer", "# This file is PRE-GENERATED by SharpFunction", " ");
        }
    }
}
